### ISSUE TITLE
logo is missing

### ISSUE THREAD

**Issue by kwhkim** [pypa/packaging.python.org#1071]
logo image link is broken in https://www.pypa.io/en/latest/
just below the paragraph of "Click the logo below to download pip, the most prominent software used to interact with PyPI."

**Comment by aniketkumar412** [comment]
It's redirecting to the download page, I think the issue has been resolved.

**Comment by bhrutledge** [comment]
The image is still broken for me:

<img width="835" alt="Screen Shot 2022-04-19 at 6 55 59 AM" src="https://user-images.githubusercontent.com/1326704/163989036-4ebb8d9b-e18b-4c90-959b-5d3b48900814.png">

However, this is an error on `pypa.io`, not `packaging.python.org`. I'm transferring this issue to the pypa.io repo.

**Comment by bhrutledge** [comment]
Oh, apparently I can't do that. Maybe @di or @pradyunsg?
